version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306/tcp"
    volumes:
      - ~/.essenceit/mysql:/var/lib/mysql
      - mysql/scripts:/mysql/scripts
  app:
    build: ./src
    ports:
      - "3000:3000"
    links:
      - mysql